test:
  imports:
    - {{ cookiecutter.project_slug }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupitervolta/{{ cookiecutter.project_name}}
  summary: {{ cookiecutter.project_short_description }}
  description: |
    {{ cookiecutter.project_short_description }}

extra:
  recipe-maintainers:
    - {{ cookiecutter.github_username }}
